- .editorconfig
- build.gradle
- config/checkstyle/naver-checkstyle-rules.xml
- config/checkstyle/naver-checkstyle-suppressions.xml
- close #7 
- 네이버 체크스타일 적용
- 
- 
- [check style 참고 URL](https://hello-judy-world.tistory.com/211)
> chore: 네이버 check style 적용

- domain/domain-module/src/main/java/org/domainmodule/agent/entity/Agent.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/Post.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/PostImage.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/PromptHistory.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroup.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroupImage.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/type/PostLength.java
- domain/domain-module/src/main/java/org/domainmodule/rssfeed/entity/RssFeed.java
- domain/domain-module/src/main/java/org/domainmodule/rssfeed/entity/type/FeedCategory.java
- domain/domain-module/src/main/java/org/domainmodule/user/entity/Oauth.java
- domain/domain-module/src/main/java/org/domainmodule/user/entity/RefreshToken.java
- domain/domain-module/src/main/java/org/domainmodule/user/entity/User.java
- domain/domain-module/src/main/java/org/domainmodule/user/entity/type/ProviderType.java
- close #23 
- 게시물 그룹 (post_group)에서 본문길이를 int형 ENUM을 이용해 할당
- 게시글의 글자수가 커질 것 같은 컬럼은 text 타입 사용
- 
- ERD도 수정해놨는데 한번 체크정도만 해주시면 좋을 것 같습니다!
-
> chore: 엔티티 컬럼 속성 부여

- application/main-application/build.gradle
- application/main-application/src/main/java/org/mainapplication/domain/auth/controller/AuthController.java
- application/main-application/src/main/java/org/mainapplication/global/config/SwaggerConfig.java
- application/main-application/src/main/java/org/mainapplication/global/config/WebSecurityConfig.java
- application/main-application/src/main/java/org/mainapplication/global/constants/WebSecurityURI.java
- application/main-application/src/main/java/org/mainapplication/health/HealCheckController.java
- application/main-application/src/main/resources/application-oauth.yml
- application/main-application/src/main/resources/application.yml
- close #29 
- swagger 등록
- yml 파일 분리 (application.yml, application.oauth)
- token을 재발급하는 부분은 보안적으로 민감한 것 같아서 어떤 방법을 적용해서 swagger에 노출을 안시킬지 고민
- 방법 1.  @Operation(hidden = true)을 사용해 swagger에서 숨기기
- 방법 2. @Profile("dev") 을 이용해서 개발환경에서만 api가 활성되도록
- common모듈에서 구현을 해야할 지 고민했었는데 이전에 common 모듈은 제거하는 방향으로 갈 것 같아서 main-module에 구현을 했습니다.
- 
- [https://springdoc.org/#properties](https://springdoc.org/#properties)
- [https://infinitecode.tistory.com/65](https://infinitecode.tistory.com/65)
> [#29] Docs: swagger 적용

- .github/workflows/main-appliction.yml
- close #51 
- swagger 메인서버에 배포하기 위해서 gitaction 수정 후 적용
- 
- 
-
> [#51] Chore: Swagger 배포 테스트

- .github/workflows/main-appliction.yml
- application/main-application/docker/docker-compose.minipc.yml
- application/main-application/src/main/resources/application-oauth.yml
- close #55 
- main-application 자동배포 수정
- 깃허브 환경변수를 이용해 .env파일로 배포
- 
- 
-
> [#55] Chore: 멀티모듈 변경으로 인한 CI/CD 수정

- application/main-application/src/main/java/org/mainapplication/domain/post/controller/PostController.java
- application/main-application/src/main/java/org/mainapplication/domain/post/controller/request/CreatePostsRequest.java
- application/main-application/src/main/java/org/mainapplication/domain/post/exception/PostErrorCode.java
- application/main-application/src/main/java/org/mainapplication/domain/post/service/PostService.java
- close #60 
- 요청 본문 클래스인 `CreatePostsRequest`에 각 필드에 검증 어노테이션 및 에러 메시지를 추가했습니다.
- referenceType에 맞는 필드가 요청 본문에 함께 존재하는지 검증하는 로직을 PostController에 추가했습니다.
```java
// PostController
public ResponseEntity<CreatePostsResponse> createPosts( ... ) {
return switch (createPostsRequest.getReference()) {
// referenceType이 NONE인 경우
case NONE -> ResponseEntity.ok(postService.createPostsWithoutRef(createPostsRequest, limit));
// referenceType이 NEWS인 경우: newsCategory가 null이면 에러 응답
case NEWS -> {
if (createPostsRequest.getNewsCategory() == null) {
throw new CustomException(PostErrorCode.NO_NEWS_CATEGORY);
}
yield ResponseEntity.ok(postService.createPostsByNews(createPostsRequest, limit));
}
// referenceType이 IMAGE인 경우: imageUrls가 null이면 에러 응답
case IMAGE -> {
if (createPostsRequest.getImageUrls() == …
```
> [#60] Feature: 게시물 생성 API 및 추가 생성 API 검증 로직 추가

- .github/workflows/schedule-application.yml
- application/upload-schedule-application/build.gradle
- application/upload-schedule-application/docker/Dockerfile
- application/upload-schedule-application/docker/docker-compose.minipc.yml
- application/upload-schedule-application/scripts/minipc-docker-deploy.sh
- close #61 
- 스케쥴링 서버도 배포완료 했습니다
- 
- 단순 서버 배포작업이라 기존과 동일한 코드를 수정해서 적용했습니다!
-
> [#61] Chore: upload-schedule-application 모듈 배포

- application/main-application/src/main/java/org/mainapplication/global/constants/UrlConstants.java
- close #76 
- localhost:3000, 배포 도메인 cors 허용
- 
- 
-
> [#76] Chore: 로컬, 배포 도메인 cors 허용

- application/main-application/src/main/java/org/mainapplication/domain/post/controller/PostController.java
- application/main-application/src/main/java/org/mainapplication/domain/post/controller/request/UpdatePostRequest.java
- application/main-application/src/main/java/org/mainapplication/domain/post/exception/PostErrorCode.java
- application/main-application/src/main/java/org/mainapplication/domain/post/service/PostService.java
- application/main-application/src/main/java/org/mainapplication/domain/post/service/PostTransactionService.java
- application/main-application/src/main/java/org/mainapplication/domain/post/service/PromptHistoryService.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/Post.java
- close #74 
- 프롬프트 개별 게시물 수정
- 
- 시연 후 최대한 빨리 리펙토링을 진행하면 좋을 것 같습니다!. postService에 openapi로 글을 생성하는 로직도 있고, 이런 부분을 따로 명확하게 분리를 하면 좋을 것 같아요!
-
> [#74] Feature: 게시물 프롬프트 기반 수정 API: 개별 수정

- application/main-application/src/main/java/org/mainapplication/domain/post/exception/PostErrorCode.java
- domain/domain-module/src/main/java/org/domainmodule/post/repository/PromptHistoryRepository.java
> Fix: 쿼리 오타 수정

- application/main-application/src/main/java/org/mainapplication/domain/post/controller/PostController.java
- application/main-application/src/main/java/org/mainapplication/domain/post/controller/request/MultiplePostUpdateRequest.java
- application/main-application/src/main/java/org/mainapplication/domain/post/controller/request/SinglePostUpdateRequest.java
- application/main-application/src/main/java/org/mainapplication/domain/post/service/PostService.java
- application/main-application/src/main/java/org/mainapplication/domain/post/service/PostTransactionService.java
- application/main-application/src/main/java/org/mainapplication/global/config/WebSecurityConfig.java
- application/main-application/src/main/java/org/mainapplication/global/constants/UrlConstants.java
- application/main-application/src/main/java/org/mainapplication/global/constants/WebSecurityURI.java
- close #87 
- 프롬프트 일괄 수정 기능 구현
- 비동기 처리로 리펙토링
- server 도메인 cors 허용
- 
- 
-
> [#87]Feature: 프롬프트 일괄 수정 & 서버 도메인 CORS 에러 수정

- .github/workflows/main-appliction.yml
- close #102 
- 빌드 시 최신 커밋 반영
- clean build로 진행
- 
- 
-
> [#102] Chore: clean build 후 bootjar파일 생성 &  fetch-depth으로 전체 커밋 내역 가져요기

- .github/workflows/main-appliction.yml
- domain/domain-module/src/main/java/org/domainmodule/post/repository/PostRepository.java
- close #
- ci/cd 단계에서 clean build
- 
- 
-
> release 0.0.9

- .github/workflows/main-appliction.yml
- application/main-application/build.gradle
- close #106 
- 외부 모듈 (domain, open-ai..) 수정 시 메인 모듈서버 배포되도록 설정
- 
- 
-
> chore: 외부 모듈 수정 시 main모듈 자동배포

- .github/workflows/main-appliction.yml
- application/main-application/build.gradle
> Release v0.0.10

- .github/workflows/main-appliction.yml
> chore: fetch-depth: 0 최신 코드로 배포하도록 설정

- .github/workflows/main-appliction.yml
- application/main-application/build.gradle
- close #
- 최신 커밋 기준으로 re-run all job 수행되도록 설정
- 
- 
-
> Release v0.0.11

- application/main-application/src/main/java/org/mainapplication/MainApplication.java
> chore: ci/cd 테스트

- application/main-application/src/main/java/org/mainapplication/domain/sns/token/SnsTokenService.java
- application/main-application/src/main/java/org/mainapplication/domain/sns/twitter/TwitterService.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/config/AsyncConfig.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/post/PostService.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/service/UploadPostService.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/snstoken/SnsTokenService.java
- inner-system/sns-client/src/main/java/org/snsclient/twitter/exception/ThrowingFunction.java
- inner-system/sns-client/src/main/java/org/snsclient/twitter/service/TwitterApiService.java
- close #95 
- 비동기로 post 업로드 하는 부분을 @Async를 이용해서 처리하도록 수정하였습니다
- 
- 트랜젝션을 어느 부분에서 걸어야 할지, 특히 비동기 처리 부분에서 어디에다가 걸어야 좋을 지 더 공부해보고 추후에 수정을 해야할 것 같습니다.
- 예외를 어떤 계층에서 던져야 할 지 고민이 드네요. 일단은 twitter api를 요청하는 클래스 위에서 예외를 받아 던지는 방향으로 진행하긴 했습니다
- 서브 브랜치를 생성해서 Custom Exception 등 지저분한 코드를 리펙토링 할 계획입니다
- 
-
> [#95] Refactor: sns 업로드 비동기 리펙토링

- application/main-application/src/main/java/org/mainapplication/domain/sns/token/SnsTokenService.java
- application/main-application/src/main/java/org/mainapplication/domain/sns/twitter/TwitterService.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/config/AsyncConfig.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/exception/TwitterUploadExceptionHandler.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/post/PostService.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/service/UploadPostService.java
- application/upload-schedule-application/src/main/java/org/uploadscheduleapplication/snstoken/SnsTokenService.java
- inner-system/sns-client/src/main/java/org/snsclient/twitter/exception/ThrowingFunction.java
- inner-system/sns-client/src/main/java/org/snsclient/twitter/service/TwitterApiService.java
- close #116 
- Exception TwitteUploadExceptionHandler로 따로 분리
- 
- 
-
> [#116] Refactor: tweet upload exception 분리

- inner-system/sns-client/src/main/java/org/snsclient/twitter/service/TwitterMediaUploadService.java
> refactor: media upload 요청 중 예외 처리

- application/main-application/src/main/java/org/mainapplication/domain/post/service/PostService.java
- application/main-application/src/main/java/org/mainapplication/openai/prompt/CreatePostPromptTemplate.java
- close #124 
1. Instruction에서 역할 지정하는 부분을 '20대 중반 남성'에서 '20대 중반 여성'으로 변경하고, 부드러운 말투와 이모지를 사용하도록 지정했습니다.
2. Instruction에서 답변 포맷을 지정하는 내용을 추가했습니다. 특히 summary 필드에 들어가야 하는 내용을 명사형으로 한정시켜서, 화면에 보일 게시물 요약제목이 일관성있게 보이도록 수정했습니다.
3. CreatePostPrompt 클래스명을 CreatePostPromptTemplate으로 변경했습니다.
> [#124] Feature: 게시물 생성 시 사용되는 Instruction 프롬프트를 UT 요구사항에 맞게 변경

- application/main-application/src/main/java/org/mainapplication/domain/post/controller/PostController.java
- application/main-application/src/main/java/org/mainapplication/domain/post/controller/request/UpdatePostsRequest.java
- close #130 
- PostController 특정 API에 누락된 @Validated를 추가했습니다.
- UpdatePostsRequest 내 클래스 타입 필드에 @Valid를 추가했습니다.
> [#130] Fix: 검증 누락된 API 수정

- application/main-application/src/main/resources/application.yml
- domain/domain-module/src/main/resources/application-domain.yml
- application-domain.yml에 jpa timezone 설정 추가
> Release v0.0.16

- .env.example
- application/main-app/src/main/resources/application-aws.yml
- application/main-app/src/main/resources/application-dev.yml
- application/main-app/src/main/resources/application-prod.yml
- application/main-app/src/main/resources/application.yml
- domain/domain-module/src/main/resources/application-domain.yml
- close #138 
- application.yml 파일 분리
- 배포 환경 : application-prod.yml 실행
- 개발 환경: application-dev.yml 실행
- 
- 
-
> [#138] Style: 개발환경, 배포환경 logging 레벨 분리

- domain/domain-module/src/main/java/org/domainmodule/post/entity/Post.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/PostImage.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/PromptHistory.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroup.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroupImage.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroupRssCursor.java
- domain/domain-module/src/main/java/org/domainmodule/user/entity/Oauth.java
- close #56
@Builder를 사용한 정적 팩토리 메서드가 구현되어 있는 모든 엔티티에 빌더 접근 제한을 적용하였습니다.
> [#56] domain 모듈에서 엔티티 @Builder 접근 제한 일괄 적용

- application/main-app/src/main/java/org/mainapp/domain/agent/controller/AgentController.java
- application/main-app/src/main/java/org/mainapp/domain/agent/controller/response/GetAgentPlanResponse.java
- application/main-app/src/main/java/org/mainapp/domain/agent/service/AgentService.java
- domain/domain-module/src/main/java/org/domainmodule/agent/repository/AgentRepository.java
- close #171 
- SNS 계정별 요금제 조회
- 
- 
-
> [#171]Feature: Agent 계정 요금제 타입 조회

- application/main-app/src/main/java/org/mainapp/domain/post/controller/response/type/PostResponse.java
- close #198 
프론트 측 요청에 따라 PostResponse에 postGroupId 필드를 추가했습니다.
> [#198] Feature: PostResponse에 postGroupId 필드 추가

- application/main-app/src/main/java/org/mainapp/global/filter/JwtAuthenticationFilter.java
- domain/domain-module/src/main/java/org/domainmodule/post/entity/Post.java
- close #203 
- Post - PostImage
- Post - PromptHistory  Cascade, orphanRemoval 설정
`@OneToMany(mappedBy = "post", cascade = CascadeType.REMOVE, orphanRemoval = true)
private List<PostImage> postImages = new ArrayList<>();
@OneToMany(mappedBy = "post", cascade = CascadeType.REMOVE, orphanRemoval = true)
private List<PromptHistory> promptHistories = new ArrayList<>();`
- 
- 
-
> [#203] Fix: Post와 PromptHistory, PostImage orphanRemoval 설정

- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/TwitterController.java
- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/TwitterService.java
- application/main-app/src/main/java/org/mainapp/global/config/WebSecurityConfig.java
- application/main-app/src/main/java/org/mainapp/global/constants/UrlConstants.java
- application/main-app/src/main/java/org/mainapp/global/filter/JwtAuthenticationFilter.java
- application/main-app/src/main/java/org/mainapp/global/oauth2/handler/CustomOAuth2SuccessHandler.java
- application/main-app/src/main/java/org/mainapp/global/util/JwtUtil.java
- close #215 
- 로그인 성공 시 REDIRECT_URL을 설정해서 이동하도록 설정
- 
- 
-
> [#215] Refactor: 구글, 트위터 로그인 후 리다이렉트 URL적용

- application/main-app/src/main/java/org/mainapp/global/config/WebSecurityConfig.java
- close #219 
- cors설정한 부분이 적용이 안된게 발견이 되어서 수정했습니다
- 
- 
-
> [#219] Refactor:  cors @Bean 설정  적용

- application/main-app/src/main/java/org/mainapp/domain/agent/service/AgentService.java
- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/TwitterController.java
- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/TwitterService.java
- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/response/TwitterRedirectResponse.java
- application/main-app/src/main/java/org/mainapp/global/config/WebSecurityConfig.java
- application/main-app/src/main/java/org/mainapp/global/constants/WebSecurityURI.java
- clients/sns-client/src/main/java/org/snsclient/twitter/service/TwitterApiService.java
- 트위터 로그인 방식 변경
1. twitter/login 요청
2. redirecturl을 클라이언트에게 전송
3. 클라이언트에서 x로그인으로 진입
4. 성공시 리다이렉트
> Release v0.0.27

- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/TwitterController.java
- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/response/TwitterRedirectResponse.java
> Release v.0.0.26

- application/main-app/src/main/java/org/mainapp/domain/agent/service/AgentService.java
- close #233 
- 트위터 로그인 로직에서 구글 아이디 2개에 트위터 아이디 1개를 등록할 수 있는 상태인데, 이 부분을 어떻게 할지 정해야할 것 같습니다!
- 
- 
-
> [#233] Docs: 트위터 계정 로그인/회원가입 로직변경 할 부분 TODO 등록

- application/main-app/src/main/java/org/mainapp/domain/agent/controller/request/UpdateAgentPersonalSettingRequest.java
- application/main-app/src/main/java/org/mainapp/domain/agent/service/AgentService.java
- application/main-app/src/main/java/org/mainapp/domain/post/controller/response/GetPostGroupPostsResponse.java
- application/main-app/src/main/java/org/mainapp/domain/post/controller/response/type/PostResponse.java
- application/main-app/src/main/java/org/mainapp/domain/post/service/PostCreateService.java
- application/main-app/src/main/java/org/mainapp/openai/prompt/CreatePostPromptTemplate.java
- domain/domain-module/src/main/java/org/domainmodule/agent/entity/AgentPersonalSetting.java
- close #228 
- 목적에 따라 1개의 프롬프트를 공통으로 적용했었던 부분을 PostPurpose에 맞게 개별적으로 적용되도록 수정했습니다.
INFORMATION("정보 전달") -> getInformationPrompt()
OPINION("의견 표출") -> getOpinionPrompt()
HUMOR("유머") -> getHumorPrompt()
MARKETING("마케팅/홍보") -> getMarketingPrompt()
글 목적 : 마케팅
주제 : 빨간색 마우스
내용 : 마우스의 사용감이 좋은걸 강조해줘
**요약** : 빨간색 마우스의 매력과 뛰어난 사용감을 강조한 마케팅 게시물.
**내용1** : 여러분, 컴퓨터를 사용할 때 작은 소품 하나가 우리의 감정을 얼마나 변화시킬 수 있는지 아시나요? 바로 이 빨간색 마우스에 대해 이야기해볼게요! 😊\n\n그 매력적인 디자인은 눈에 띄는 레드 컬러로, 열정과 활력을 불어넣어줘요. 어떤 사무실이나 게이밍 공간에서도 이 마우스 하나면 분위기가 완전히 달라진답니다. \n\n그리고 무엇보다 중요하게 느껴지는 건 바로 사용감이에요! 인체공학적으로 설계된 그립감은 손에 착 감겨서 오랫동안 사용해도 피로감이 없어요. 어떤 작업이든, 게임이든 이 마우스와 함께라면 집중력이 쑥쑥 올라간답니다.\n\n느낌 좋은 디자인과 뛰어난 사용감! 이 빨간색 마우스와 함께라면, 매일의 일상이 더 즐거워질 거예요. 지금 바로 업그레이드해 보세요! 🎉 #마우스 #디자인 #게이밍 #업그레이드
**요약** : 게이밍 마우스의 색상이 플레이에 미치는 심리적 영향을 탐구하며, 제품의 …
> [#228] Docs: 목적 설정에 따른 프롬프트 개별 설정

- application/main-app/src/main/java/org/mainapp/openai/prompt/CreatePostPromptTemplate.java
- close #235 
- 게시물 생성 시 답변 형식을 지정하는 프롬프트를 추가했습니다. 제목으로 사용되는 요약 내용이 확실히 간결하고 명확해졌어요!
- 뉴스 참고 게시물 생성 시, 관련이 크게 없는 주제가 입력되더라도 최대한 관련지어 답변을 생성할 수 있도록 프롬프트를 추가했습니다.
> [#235] Chore: 게시물 생성 시 답변 형식 지정 프롬프트 추가

- application/main-app/src/main/java/org/mainapp/domain/sns/twitter/TwitterService.java
- application/main-app/src/main/java/org/mainapp/global/config/WebSecurityConfig.java
- application/main-app/src/main/java/org/mainapp/global/oauth2/handler/CustomOAuth2SuccessHandler.java
- close #239
- 구글, 트위터 로그인 후 배포 URL로 리다이렉트하도록 수정
- https 요청만 받도록 필터설정
- 
- 
-
> [#239] Chore: 배포 URL로 리다이렉트

- application/main-app/src/main/java/org/mainapp/global/config/WebSecurityConfig.java
> Refactor: https requrie 비활성화

- application/main-app/src/main/java/org/mainapp/domain/post/controller/PostController.java
- application/main-app/src/main/java/org/mainapp/domain/post/controller/request/UpdateReservedPostsRequest.java
- application/main-app/src/main/java/org/mainapp/domain/post/controller/request/type/UpdateReservedPostsRequestItem.java
- application/main-app/src/main/java/org/mainapp/domain/post/service/PostService.java
- application/main-app/src/main/java/org/mainapp/domain/post/service/PostUpdateService.java
- domain/domain-module/src/main/java/org/domainmodule/post/repository/PostRepository.java
- close #246 
- 작성중...
- 
- 
-
> [#246] Feature: 계정별 예약 게시물 예약일시 수정 API 구현

- application/main-app/src/main/java/org/mainapp/global/constants/HeaderConstants.java
- close #252 
- 쿠키값에 RefreshToken로 들어가던 부분을 refreshToken을 수정
- 
- 
-
> [#252] Refactor: 쿠키설정시 key값을 RefreshToken -> refreshToken으로 네이밍 변경

- domain/domain-module/src/main/java/org/domainmodule/rssfeed/entity/type/FeedCategoryType.java
- close #254
새롭게 추가될 RSS 피드 카테고리를 반영했습니다.
서비스 중단을 방지하기 위해 기존 카테고리를 남겨두었고, 이번 변경사항이 배포되면 DB 테이블을 수정한 뒤 불필요한 카테고리를 순차적으로 제거할 예정입니다.
> [#254] Feature: RSS 피드 변경 - 신규 뉴스 카테고리 추가

- application/main-app/src/main/java/org/mainapp/global/constants/UrlConstants.java
- close #262 
- 구매한 도메인 적용해서 프론트 리다이렉트  URL 수정했습니다
- 
- 
-
> [#262] Style: 프론트 배포 도메인 변경

- application/main-app/src/main/java/org/mainapp/domain/post/service/PostService.java
- close #261 
- 게시글 내용 사용자가 변경시 PostStatus값이 EDITING(수정중)으로 변경되도록 수정하였습니다.
- 
- 
-
> [#261] Refactor: post 내용 변경 시 상태값 EDITING으로 변경

- application/main-app/src/main/java/org/mainapp/domain/newscategory/service/NewsCategoryService.java
- domain/domain-module/src/main/java/org/domainmodule/rssfeed/entity/RssFeed.java
- domain/domain-module/src/main/java/org/domainmodule/rssfeed/entity/type/FeedCategoryType.java
- domain/domain-module/src/main/java/org/domainmodule/rssfeed/repository/RssFeedRepository.java
- close #255 
- RssFeed 엔티티에 isActivated 필드를 추가하여 활성화 여부를 구분하도록 수정했습니다.
- 뉴스 카테고리 목록 조회 API 호출 시, 비활성화된 피드는 필터링하여 응답하지 않도록 로직을 변경했습니다.
- 신규로 추가된 뉴스 카테고리를 반영했습니다.
> [#255] Feature: RSS 피드 변경 - 신규 카테고리 추가 및 비활성화 피드 필터링 로직 추가

- clients/sns-client/src/main/java/org/snsclient/twitter/service/TwitterApiService.java
- close #276 
- 트위터 계정 추가 버튼 클릭시 계정 선택창이 나오도록 수정했습니다
- 아직 테스트를 잘못해서 배포된 사이트로 확인 후 이상있으면 롤백하겠스빈다!
- 
-
> [#276] Refactor: 트위터 로그인 시 계정 선택화면이 나오도록 수정

- clients/open-ai-client/src/main/java/org/openaiclient/client/OpenAiClient.java
- clients/sns-client/src/main/java/org/snsclient/twitter/service/TwitterApiService.java
> Release v0.0.38

- application/main-app/src/main/java/org/mainapp/domain/v1/sns/twitter/LegacyTwitterController.java
- close #298 
이후 작업을 위해 Twitter 관련 API도 버저닝 적용했습니다.
> [#298] Chore: twitter api 버저닝

- application/main-app/src/main/java/org/mainapp/openai/prompt/CreatePostPromptTemplate.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/type/PostGroupLengthType.java
- close #300 
회의 중 제안되었던 프롬프트 개선사항을 반영했습니다.
1. 자연스러운 줄바꿈 추가
2. 글자수 제한 누락 문제 해결
3. 말투 지정 누락 문제 해결
4. 모든 문장마다 이모지를 사용하지 않도록 개선
PostGroupLengthType에 잘못 지정된 글자수 제한을 변경했습니다.
> [#300] Chore: 프롬프트 개선사항 반영

- application/main-app/src/main/java/org/mainapp/domain/v1/post/controller/PostController.java
- application/main-app/src/main/java/org/mainapp/domain/v1/post/controller/response/GetPostGroupStepResponse.java
- application/main-app/src/main/java/org/mainapp/domain/v1/post/service/PostService.java
- application/main-app/src/main/java/org/mainapp/domain/v1/post/service/PostUpdateService.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroup.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/type/PostGroupStepType.java
- close #310 
- PostGroupStepType 열거형 추가 + PostGroup에 step 필드 추가했습니다.
- PostGroup의 step만 조회하는 API를 추가했습니다.
- dev / main에 병합 전에 스키마 변경을 수행해야 합니다.
> [#310] Feature: 게시물 그룹 단계 조회 API 추가

- application/main-app/src/main/java/org/mainapp/domain/v1/post/controller/PostController.java
- application/main-app/src/main/java/org/mainapp/domain/v1/post/controller/request/UpdatePostGroupStepRequest.java
- application/main-app/src/main/java/org/mainapp/domain/v1/post/service/PostService.java
- domain/domain-module/src/main/java/org/domainmodule/postgroup/entity/PostGroup.java
- close #313 
- 게시물 그룹 단계 변경 API를 추가했습니다.
- 기존 PostGroup 생성 메서드에, step을 지정하는 부분을 추가했습니다.
> [#313] Feature: 게시물 그룹 단계 변경 API 추가
